# https://yamllint.readthedocs.io/en/stable/
---
extends: default

rules:
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: -1
    max-spaces-inside-empty: -1
  comments:
    require-starting-space: true
    min-spaces-from-content: 1
  comments-indentation: disable
  document-start: enable
  truthy: enable
  line-length:
    max: 250
    level: warning
  new-line-at-end-of-file: enable
  octal-values:
    forbid-explicit-octal: true
    forbid-implicit-octal: true
