---
- name: Install dependencies
  ansible.builtin.apt:
    state: latest
    update_cache: yes
    name:
      - apt-transport-https
  tags:
    - docker
    - system

- name: DEB architecture
  ansible.builtin.shell: dpkg --print-architecture
  register: deb_architecture
  changed_when: false
  tags:
    - docker

- name: "Add Docker archive key: {{ docker_key_file }}"
  ansible.builtin.get_url:
    url: "{{ docker_key_url }}"
    dest: "{{ docker_key_file }}"
  tags:
    - docker

- name: Add Docker repository
  ansible.builtin.apt_repository:
    state: present
    update_cache: yes
    repo: "deb [arch={{ deb_architecture.stdout }} signed-by={{ docker_key_file }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable"
    filename: docker
  tags:
    - docker

- name: Install packages
  ansible.builtin.apt:
    state: latest
    update_cache: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
  tags:
    - docker

- name: Set Docker service state
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  tags:
    - docker
