---
- name: Install dependencies
  ansible.builtin.apt:
    state: latest
    update_cache: yes
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - gnupg-agent
      - software-properties-common
      - python3-setuptools
      - python3-pip
      - python3-venv
  tags:
    - docker
    - system

- name: Add Docker GPG apt key
  ansible.builtin.apt_key:
    state: present
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    keyring: /etc/apt/trusted.gpg.d/docker.gpg
  tags:
    - docker

- name: Add Docker repository
  ansible.builtin.apt_repository:
    state: present
    update_cache: yes
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable"
    filename: docker
  tags:
    - docker

- name: Install docker-ce
  ansible.builtin.apt:
    state: latest
    update_cache: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  tags:
    - docker

- name: Set Docker service state
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  tags:
    - docker

- name: Install Docker module for Python
  ansible.builtin.pip:
    name: docker
  tags:
    - docker

- name: Install docker-compose
  ansible.builtin.script: scripts/install-docker-compose
  args:
    creates: /usr/local/bin/docker-compose
  tags:
    - docker
    - docker-compose
