#!/usr/bin/env bash
# https://docs.docker.com/compose/install/

REPO="docker/compose"
BIN_NAME="docker-compose"
FILE_NAME="${BIN_NAME}-$(uname -s)-$(uname -m)"
TARBALL_URL=$(curl --silent "https://api.github.com/repos/${REPO}/releases/latest" | jq -r .tarball_url)
VERSION=$(grep -o '[^/v]*$' <<< "${TARBALL_URL}")
INSTALL_PATH="/usr/local/bin"

curl --silent -Lo "/tmp/${BIN_NAME}" "https://github.com/${REPO}/releases/download/${VERSION}/${FILE_NAME}"

install "/tmp/${BIN_NAME}" "${INSTALL_PATH}/${BIN_NAME}"

rm "/tmp/${BIN_NAME}"
